backend/abyssal_api/urls.py
from django.urls import path

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

import abyssal_api.views as views


app_name = "abyssal_api"


schema_view = get_schema_view(
    openapi.Info(
        title="Abyssal API",
        default_version="v1",
        description="Test description",
        license=openapi.License(name="MIT License"),
    ),
    authentication_classes=[],
    public=True,
)

urlpatterns = [
    path(
        "old/type/<int:type_id>/available/",
        views.AvailableTypedModuleListAPI.as_view(),
        name="module_list",
    ),
    path(
        "old/type/<int:type_id>/assets/",
        views.AssetOwnedListAPI.as_view(),
        name="asset_list",
    ),
    path(
        "old/creator/<int:creator_id>/",
        views.CreatorModuleListAPI.as_view(),
        name="creator_list",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("modules/", views.ModuleView.as_view()),
    path("modules/<int:pk>/", views.ModuleDetailView.as_view(), name="module_detail"),
    path("modules/<int:pk>/appraisal/", views.ModuleAppraisalView.as_view()),
    path("types/", views.TypeListView.as_view()),
    path("creators/<int:pk>/", views.CreatorDetailView.as_view()),
    path("creators/<int:pk>/creations/", views.CreatorCreationListView.as_view()),
]

backend/abyssal_market/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("eve_auth.urls", namespace="eve_auth")),
    path("api/", include("abyssal_api.urls", namespace="abyssal_api")),
    path("faq/", TemplateView.as_view(template_name="help.html"), name="faq"),
    path("legal/", TemplateView.as_view(template_name="legal.html"), name="legal"),
    path(
        "support/", TemplateView.as_view(template_name="support.html"), name="support"
    ),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt")),
    path("", include("abyssal_modules.urls", namespace="abyssal_modules")),
    path("", include("django_prometheus.urls")),
]

backend/abyssal_modules/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

import abyssal_modules.views


app_name = "abyssal_modules"

urlpatterns = [
    path(
        "type/<int:type_id>/<str:referer>/similar/<int:module_id>/",
        abyssal_modules.views.SimilarModuleRedirect.as_view(),
        name="similar_view",
    ),
    path(
        "module/<int:module_id>/similar/",
        abyssal_modules.views.SimilarModuleRedirect.as_view(),
        name="similar_view",
    ),
    path(
        "type/<int:type_id>/",
        RedirectView.as_view(
            pattern_name="abyssal_modules:type_module_list", permanent=True
        ),
    ),
    path(
        "type/<int:type_id>/contracts/",
        abyssal_modules.views.TypedModuleList.as_view(),
        name="type_module_list",
    ),
    path(
        "type/<int:type_id>/hof/",
        abyssal_modules.views.HallOfFameView.as_view(),
        name="type_hall_of_fame",
    ),
    path(
        "type/<int:type_id>/assets/",
        abyssal_modules.views.TypeAssetModuleList.as_view(),
        name="type_asset_module_list",
    ),
    path(
        "type/<int:type_id>/roll/",
        abyssal_modules.views.RollCalculatorView.as_view(),
        name="roll_calculator",
    ),
    path(
        "module/<int:pk>/",
        abyssal_modules.views.ModuleView.as_view(),
        name="module_view",
    ),
    path(
        "module/<int:pk>/image/",
        abyssal_modules.views.ModuleImageView.as_view(),
        name="module_image_view",
    ),
    path(
        "creator/<int:pk>/",
        abyssal_modules.views.CreatorView.as_view(),
        name="creator_view",
    ),
    path(
        "view_contract/",
        abyssal_modules.views.OpenContractView.as_view(),
        name="open_contract",
    ),
    path("appraisal/", abyssal_modules.views.AppraisalView.as_view(), name="appraisal"),
    path(
        "statistics/", abyssal_modules.views.StatisticsList.as_view(), name="statistics"
    ),
    path("", abyssal_modules.views.ModuleList.as_view()),
]

backend/eve_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

import eve_auth.views


app_name = "eve_auth"


urlpatterns = [
    path("login/", eve_auth.views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("callback/", eve_auth.views.CallbackView.as_view(), name="callback"),
    path("profile/", eve_auth.views.ProfileView.as_view(), name="profile"),
]

backend/abyssal_modules/models/characters.py
from django.db import models

from eve_esi import ESI, EsiException
import swagger_client.api.character_api

class EveCharacterManager(models.Manager):
    def get_or_create_by_id(self, character_id):
        try:
            return self.model.objects.get(id=character_id)
        except self.model.DoesNotExist:
            client = swagger_client.api.character_api.CharacterApi()
            (r, c, _) = client.get_characters_character_id_with_http_info(character_id=character_id)

            if c != 404:
                character_name = r.name
            else:
                character_name = "DELETED CHARACTER"

            character, _ = EveCharacter.objects.update_or_create(
                id=character_id, defaults={"name": character_name}
            )

            return character


class EveCharacter(models.Model):
    objects = EveCharacterManager()

    id = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

backend/abyssal_modules/models/mutators.py
from django.db import models


class Mutator(models.Model):
    item_type = models.OneToOneField(
        "eve_sde.InvType", models.CASCADE, related_name="+"
    )
    result = models.ForeignKey("ModuleType", models.CASCADE)

    applicable_modules = models.ManyToManyField("eve_sde.InvType")
    attributes = models.ManyToManyField("TypeAttribute", through="MutatorAttribute")


class MutatorAttribute(models.Model):
    mutator = models.ForeignKey("Mutator", models.CASCADE)
    attribute = models.ForeignKey("TypeAttribute", models.CASCADE)

    min_modifier = models.DecimalField(max_digits=10, decimal_places=5)
    max_modifier = models.DecimalField(max_digits=10, decimal_places=5)

backend/abyssal_modules/forms.py
import re

from django import forms


class ModuleLinkForm(forms.Form):
    text = forms.CharField(label="Copied text", max_length=4000)

    def clean_text(self):
        match = re.search(r"<url=showinfo:(\d+)//(\d+)>", self.cleaned_data["text"])

        if match is None:
            raise forms.ValidationError("No module link found")

        return (int(match.group(1)), int(match.group(2)))

backend/abyssal_modules/views.py
from django.shortcuts import render
from django.core.cache import cache
from django.views import View
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from django.http import HttpResponse, FileResponse, Http404, HttpResponseRedirect
from django.db.models import Count, F, Window
from django.db.models.functions import Trunc
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.contrib.staticfiles import finders

from wand.color import Color
from wand.image import Image
from wand.drawing import Drawing
from wand.compat import nested

from abyssal_modules.models.modules import Module, ModuleType, StaticModule
from abyssal_modules.models.attributes import TypeAttribute, ModuleAttribute
from abyssal_modules.models.characters import EveCharacter
from abyssal_modules.models.mutators import Mutator, MutatorAttribute
from eve_esi import ESI
from eve_auth.models import EveUser
from price_predictor.utils import predict_price
from abyssal_modules.forms import ModuleLinkForm
from abyssal_modules.tasks import create_module
from abyssal_modules.utils import (
    format_attribute_basic,
    render_attribute_value,
    correct_high_is_good,
    base_high_is_good,
)

import logging

logger = logging.getLogger(__name__)


class SimilarModuleRedirect(View):
    def get(self, request, module_id, type_id=None, referer=None):
        if referer == "assets":
            referer = "abyssal_modules:type_asset_module_list"
        elif referer == "contracts":
            referer = "abyssal_modules:type_module_list"
        else:
            # Default redirection.
            referer = "abyssal_modules:type_module_list"
        module = Module.objects.get(id=module_id)
        if type_id == None:
            type_id = module.type_id
        attributes = module.attribute_dict()
        parameters = ""
        data = request.GET
        for key in attributes.keys():
            if attributes[key]["display"]:
                if f"{key}_check" not in data.keys() or data[f"{key}_check"] == "true":
                    parameters += f"{key}={attributes[key]['real_value']}&"

        if "percent_range" in data.keys():
            parameters += f"percent_range={float(data['percent_range']) / 100}"
        else:
            parameters += f"percent_range=0.2"

        rev = reverse(referer, kwargs={"type_id": type_id})
        return HttpResponseRedirect(f"{rev}?{parameters}")


class ModuleList(View):
    def get(self, request):
        return render(
            request,
            "abyssal_modules/home.html",
        )


class TypedModuleList(View):
    def get(self, request, type_id):
        try:
            module_type = ModuleType.objects.get(id=type_id)
        except ModuleType.DoesNotExist:
            raise Http404("Module type does not exist.")

        attributes = module_type.attribute_list

        return render(
            request,
            "abyssal_modules/list.html",
            {"module_type": module_type, "attributes": attributes},
        )


class TypeAssetModuleList(LoginRequiredMixin, View):
    def get(self, request, type_id):
        try:
            module_type = ModuleType.objects.get(id=type_id)
        except ModuleType.DoesNotExist:
            raise Http404("Module type does not exist.")

        attributes = module_type.attribute_list

        return render(
            request,
            "abyssal_modules/asset_list.html",
            {"module_type": module_type, "attributes": attributes},
        )


class RollCalculatorView(View):
    def get(self, request, type_id):
        try:
            module_type = ModuleType.objects.get(id=type_id)
        except ModuleType.DoesNotExist:
            raise Http404("Module type does not exist.")

        mutators = Mutator.objects.filter(result=module_type).order_by(
            "item_type__name"
        )
        modules = StaticModule.objects.filter(type=module_type)
        attributes = TypeAttribute.objects.filter(
            mutatorattribute__mutator__result=module_type
        ).distinct("attribute")

        return render(
            request,
            "abyssal_modules/roll_calculator.html",
            {
                "module_type": module_type,
                "modules": modules,
                "mutators": mutators,
                "module_stats": {m.id: m.as_dict() for m in modules},
                "mutator_stats": {
                    m.item_type.id: {
                        x.attribute.attribute.id: (x.min_modifier, x.max_modifier)
                        for x in m.mutatorattribute_set.all()
                    }
                    for m in mutators
                },
                "attributes": attributes,
            },
        )


class HallOfFameView(View):
    def get(self, request, type_id):
        try:
            module_type = ModuleType.objects.get(id=type_id)
        except ModuleType.DoesNotExist:
            raise Http404("Module type does not exist.")

        attributes = TypeAttribute.objects.filter(
            mutatorattribute__mutator__result=module_type
        ).distinct("attribute")

        key = "HallOfFame_%d" % type_id

        res = cache.get(key)

        if res is None:
            res = {}

            for k in attributes:
                qs = ModuleAttribute.objects.filter(
                    module__type=module_type, attribute=k.attribute
                )

                d1 = qs.order_by("value")[:10]
                d2 = qs.order_by("-value")[:10]

                hig = base_high_is_good(k.high_is_good, k.attribute.id)

                res[k.id] = (k.attribute, d2 if hig else d1, d1 if hig else d2)

            cache.set(key, res, 60 * 120)

        return render(
            request,
            "abyssal_modules/hall_of_fame.html",
            {"module_type": module_type, "hof": res},
        )


class ModuleView(DetailView):
    model = Module
    template_name = "abyssal_modules/module.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        static_modules = [
            m.as_dict()
            for m in StaticModule.objects.filter(type=self.object.type).all()
        ]

        context["prediction"] = predict_price(self.object)
        context["contracts"] = self.object.contracts.all()
        context["image_url"] = self.request.build_absolute_uri(
            reverse("abyssal_modules:module_image_view", kwargs={"pk": self.object.id})
        )

        module_attributes = self.object.as_dict()

        for v in static_modules:
            for k, vv in v["attributes"].items():
                if vv["display"]:
                    vv["delta"] = (
                        module_attributes["attributes"][k]["real_value"]
                        - vv["real_value"]
                    )

        print(static_modules)

        context["static_modules"] = static_modules

        return context


class ModuleImageView(DetailView):
    model = Module
    response_class = FileResponse

    def render_to_response(self, context, **kwargs):
        BLOCK_DISTANCE = 4
        HEADER_HEIGHT = 64
        BLOCK_HEIGHT = 36
        STAT_BAR_HEIGHT = 4
        IMG_MARGINS = 0
        INNER_WIDTH = 352

        attr_dict = self.object.as_dict()

        base_module = StaticModule.objects.get(source_id=self.object.source_id)
        base_module_dict = base_module.as_dict()["attributes"]

        all_mutators = Mutator.objects.filter(result_id=self.object.type_id)

        mutator = Mutator.objects.get(item_type_id=self.object.mutator_id)

        mutator_dicts = {
            m.id: {
                v.attribute.attribute_id: (v.min_modifier, v.max_modifier)
                for v in MutatorAttribute.objects.filter(mutator_id=m.id)
            }
            for m in all_mutators
        }

        with Drawing() as draw:
            with Image(
                width=INNER_WIDTH + 2 * IMG_MARGINS,
                height=2 * IMG_MARGINS
                + len(mutator_dicts[mutator.id]) * (BLOCK_HEIGHT + BLOCK_DISTANCE)
                + HEADER_HEIGHT,
                format="png",
                background=Color("#000000"),
            ) as img:
                img.alpha_channel = True
                img.transparent_color(Color("#000000"), alpha=0.0)
                draw.font_family = "DejaVu Sans"
                draw.fill_color = Color("#ffffff")
                draw.text(10, 20, "Abyssal Ballistic Control System")
                draw.fill_color = Color("#232f36")
                draw.rectangle(
                    left=IMG_MARGINS,
                    top=IMG_MARGINS,
                    width=INNER_WIDTH - 1,
                    height=HEADER_HEIGHT - 1,
                )
                draw.font_size = 12
                draw.push()
                draw.fill_color = Color("#ffffff")
                draw.text(IMG_MARGINS + 32 + 2, 21, self.object.source.name)
                draw.text(IMG_MARGINS + 32 + 2, 21 + 32, self.object.mutator.name)
                draw.pop()

                source_img_path = finders.find(
                    "img/types_32/%d.png" % self.object.source_id
                )
                if source_img_path is not None:
                    with Image(filename=source_img_path) as embed_img:
                        draw.composite(
                            operator="atop",
                            image=embed_img,
                            left=IMG_MARGINS,
                            top=IMG_MARGINS,
                            width=embed_img.width,
                            height=embed_img.height,
                        )

                mutator_img_path = finders.find(
                    "img/types_32/%d.png" % self.object.mutator_id
                )
                if mutator_img_path is not None:
                    with Image(filename=mutator_img_path) as embed_img:
                        draw.composite(

backend/abyssal_modules/templates/abyssal_modules/attribute_slider.html
{% load static %}
{% load module_stats %}

<div class="form-group col-12 col-md-6">
    <div class="row">
        <label class="col-6"><img src="{% static at.icon_path %}" title="{{ at.name }}"> {{ at.name }}{% if at.derived %}<span style="text-muted" title="This is a derived attribute.">*</span>{% endif %}</label>
        <div class="input-group input-group-sm col-3">
            <input type="number" class="form-control form-control-sm module-attribute-filter {{ at|rendered_high_is_good|yesno:'negative,positive' }}" id="attr-{{ at.id }}-min" data-attr-modified="{{ at.id }}" step="0.0001">
            <div class="input-group-append module-stat-unit">
                <span class="input-group-text">{{ at.unit_str }}</span>
            </div>
        </div>
        <div class="input-group input-group-sm col-3">
            <input type="number" class="form-control form-control-sm module-attribute-filter {{ at|rendered_high_is_good|yesno:'positive,negative' }}" id="attr-{{ at.id }}-max" data-attr-modified="{{ at.id }}" step="0.0001">
            <div class="input-group-append module-stat-unit">
                <span class="input-group-text">{{ at.unit_str }}</span>
            </div>
        </div>
    </div>
    <div class="row mt-2 px-4 slider-container">
        <div id="attr-{{ at.id }}-range" class="col-12 slider-{{ at.high_is_good|yesno:'positive,negative' }}"></div>
    </div>
</div>

backend/abyssal_modules/templates/abyssal_modules/creator.html
{% extends 'content_page.html' %}
{% load static %}

{% block title %}{{ object.name }}{% endblock %}

{% block header %}
<div class="container-fluid d-flex flex-column ng-scope">
    <div class="row align-items-center bg-primary check-contrast py-5">
        <div class="col-xl-9 container-alt text-light toggles-ignore mx-auto">
            <h1 class="display-3 mb-0">
                <span data-ng-bind="selected.palette.name" class="ng-binding">{{ object.name }}</span>
            </h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container my-5">
    <table class="table module-table dt-responsive" id="module-table" width="100%">
        <thead>
            <tr>
                <th width="1px">Icon</th>
                <th>Module</th>
                <th>Attributes</th>
            </tr>
        </thead>
    </table>
</div>

{% endblock %}

{% block trailing_js %}
<script>
function icon_format(mid, tid) {
    return `<a href="/module/${mid}/"><img src="https://image.eveonline.com/Type/${tid}_32.png"></a>`
}

function link_format(type_id, type_name) {
    return `<a href="/type/${type_id}/">${type_name}</a>`
}

$(document).ready(function () {
    $('#module-table').DataTable({
        "processing": true,
        "ajax": {
            url: "{% url 'abyssal_api:creator_list' creator_id=object.id %}",
            dataSrc: ''
        },
        "columns": [
            {
                'name': 'id',
                'orderable': false,
                'data': null,
                'render': function (data, type, row, meta) {
                    return icon_format(data.id, data.type_id);
                }
            },
            {
                'name': 'module',
                'data': null,
                'render': function (data, type, row, meta) {
                    return link_format(data.type_id, data.type_name);
                }
            },
            {
                'name': 'attributes',
                'data': 'attributes',
                'render': function (data, type, row, meta) {
                    return attribute_format(data);
                }
            }
        ],
        "order": []
    });
});
</script>
{% endblock %}

backend/abyssal_modules/templates/abyssal_modules/hall_of_fame.html
{% extends 'content_page.html' %}
{% load humanize %}
{% load cache %}
{% load static %}
{% load module_stats %}

{% block title %}{{ module_type.name }}{% endblock %}

{% block header %}
<div class="container-fluid d-flex flex-column ng-scope">
    <div class="row align-items-center bg-primary check-contrast py-5">
        <div class="col-xl-9 container-alt text-light toggles-ignore mx-auto">
            <h1 class="display-3 mb-0">
                <span data-ng-bind="selected.palette.name" class="ng-binding">{{ module_type.name }}</span>
            </h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content_tabs %}
<div class="container">
{% include "abyssal_modules/module_tabs.html" with active_page="hall_of_fame" %}
</div>
{% endblock %}

{% block content %}
<div class="container my-5">
    {% for k, v in hof.items %}
    <h2>{{ v.0.name }}</h2>

    <div class="row">
        <div class="col-6">
            <h4>Best Modules</h4>

            <table class="table stats-table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Module</th>
                        <th scope="col"><img src="{% static v.0.icon_path %}" title="{{ v.0.name }}"> {{ v.0.name }}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in v.1 %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><img src="https://image.eveonline.com/Type/{{ module_type.id }}_32.png" class="module-icon"><a href="{% url 'abyssal_modules:module_view' pk=c.module_id %}">Module {{ c.module_id }}</a></td>
                        <td>{{ c.value|format_attribute_simple:v.0.id }} {{ v.0.unit_str }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <h4>Worst Modules</h4>

            <table class="table stats-table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Module</th>
                        <th scope="col"><img src="{% static v.0.icon_path %}" title="{{ v.0.name }}"> {{ v.0.name }}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in v.2 %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><img src="https://image.eveonline.com/Type/{{ module_type.id }}_32.png" class="module-icon"><a href="{% url 'abyssal_modules:module_view' pk=c.module_id %}">Module {{ c.module_id }}</a></td>
                        <td>{{ c.value|format_attribute_simple:v.0.id }} {{ v.0.unit_str }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

backend/abyssal_modules/templates/abyssal_modules/module_tabs.html
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-tab nav-link {% if active_page == 'contract_sell' %}active{% endif %}" href="{% url 'abyssal_modules:type_module_list' type_id=module_type.id %}">Contracts</a>
    </li>
    <li class="nav-item" title="Coming soon!">
        <a class="nav-tab nav-link disabled" href="#">Sell Orders</a>
    </li>
    <li class="nav-item">
        <a class="nav-tab nav-link {% if active_page == 'asset_list' %}active{% endif %}" href="{% url 'abyssal_modules:type_asset_module_list' type_id=module_type.id %}">Your Modules</a>
    </li>
    <li class="nav-item">
        <a class="nav-tab nav-link {% if active_page == 'roll_calculator' %}active{% endif %}" href="{% url 'abyssal_modules:roll_calculator' type_id=module_type.id %}">Roll Calculator</a>
    </li>
    <li class="nav-item">
        <a class="nav-tab nav-link {% if active_page == 'hall_of_fame' %}active{% endif %}" href="{% url 'abyssal_modules:type_hall_of_fame' type_id=module_type.id %}">Hall of Fame</a>
    </li>
</ul>

backend/abyssal_modules/templates/abyssal_modules/statistics.html
{% extends 'content_page.html' %}
{% load cache %}

{% block title %}Statistics{% endblock %}

{% block header %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>

<div class="container-fluid d-flex flex-column ng-scope">
    <div class="row align-items-center bg-primary check-contrast py-5">
        <div class="col-xl-9 container-alt text-light toggles-ignore mx-auto">
            <h1 class="display-3 mb-0">
                <span data-ng-bind="selected.palette.name" class="ng-binding">Statistics</span>
            </h1>
            <p class="lead mb-3"><span data-ng-bind="selected.palette.desc" class="ng-binding">
            A page for stat nerds. If you're a machine learning person and you want to help improve
            the price predictor, contact me!</p>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container my-5">
    <h1>Statistics</h1>

    <h4>Modules known</h4>
    <div style="height: 300px">
        <canvas id="module-count-history"></canvas>
    </div>

    <h4>Type breakdown</h4>
    <div style="height: 300px">
        <canvas id="type-breakdown-pie"></canvas>
    </div>

    {% comment %} <h4>Available contracts</h4>

    <p class="text-muted">Coming soon, when the developer figures out how to
    not be bad at database design.</p>

    <h4>Region breakdown</h4>

    <p class="text-muted">Coming soon, when the developer figures out how to
    not be bad at database design.</p> {% endcomment %}

    <div class="row">
        <div class="col-6">
            <h4>Most prolific creators</h4>

            <table class="table stats-table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Creator</th>
                        <th scope="col">Module count</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in prolific_creators %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><img class="avatar" src="https://image.eveonline.com/Character/{{ c.id }}_32.jpg"><a href="{% url 'abyssal_modules:creator_view' pk=c.id %}">{{ c.name }}</a></td>
                        <td>{{ c.creation_count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <h4>Most traded modules</h4>

            <table class="table stats-table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Module</th>
                        <th scope="col">Contract count</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in traded_modules %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><img src="https://image.eveonline.com/Type/{{ c.type.id }}_32.png" class="module-icon"><a href="{% url 'abyssal_modules:module_view' pk=c.id %}">Module {{ c.id }}</a></td>
                        <td>{{ c.contract_count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


</div>

{% endblock %}

{% block trailing_js %}
<script>
var colours = [
    'rgb(255, 0, 41)',
    'rgb(55, 126, 184)',
    'rgb(102, 166, 30)',
    'rgb(152, 78, 163)',
    'rgb(0, 210, 213)',
    'rgb(255, 127, 0)',
    'rgb(175, 141, 0)',
    'rgb(127, 128, 205)',
    'rgb(179, 233, 0)',
    'rgb(196, 46, 96)',
    'rgb(166, 86, 40)',
    'rgb(247, 129, 191)',
    'rgb(141, 211, 199)',
    'rgb(190, 186, 218)',
    'rgb(251, 128, 114)',
    'rgb(128, 177, 211)',
    'rgb(253, 180, 98)',
    'rgb(252, 205, 229)',
    'rgb(188, 128, 189)',
    'rgb(255, 237, 111)',
    'rgb(189, 189, 189)'
]

var config_module_count_history = {
    type: 'line',
    data: {
        datasets: [{
            data: [
                {% for t, c in module_count_data %}
                {
                    't': "{{ t }}",
                    'y': {{ c }}
                },
                {% endfor %}
            ],
            backgroundColor: 'rgb(134, 32, 32)',
            lineTension: 0
        }],
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        legend: {
            position: "none"
        },
        scales: {
            xAxes: [{
                type: "time",
                time: {
                    unit: 'day',
                }
            }]
        },
    }
};


var config_type_breakdown_pie = {
    type: 'pie',
    data: {
        datasets: [{
            data: [
                {% for n, c in type_breakdown %}{{ c }},{% endfor %}
            ],
            backgroundColor: colours,
        }],
        labels: [
            {% for n, c in type_breakdown %}"{{ n }}",{% endfor %}
        ]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        legend: {
            position: "right"
        }
    }
};

window.onload = function() {
    new Chart(document.getElementById('module-count-history').getContext('2d'), config_module_count_history);

    new Chart(document.getElementById('type-breakdown-pie').getContext('2d'), config_type_breakdown_pie);
};

</script>
{% endblock %}