backend/abyssal_market/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("eve_auth.urls", namespace="eve_auth")),
    path("api/", include("abyssal_api.urls", namespace="abyssal_api")),
    path("faq/", TemplateView.as_view(template_name="help.html"), name="faq"),
    path("legal/", TemplateView.as_view(template_name="legal.html"), name="legal"),
    path(
        "support/", TemplateView.as_view(template_name="support.html"), name="support"
    ),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt")),
    path("", include("abyssal_modules.urls", namespace="abyssal_modules")),
    path("", include("django_prometheus.urls")),
]

backend/abyssal_modules/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

import abyssal_modules.views


app_name = "abyssal_modules"

urlpatterns = [
    path(
        "type/<int:type_id>/<str:referer>/similar/<int:module_id>/",
        abyssal_modules.views.SimilarModuleRedirect.as_view(),
        name="similar_view",
    ),
    path(
        "module/<int:module_id>/similar/",
        abyssal_modules.views.SimilarModuleRedirect.as_view(),
        name="similar_view",
    ),
    path(
        "type/<int:type_id>/",
        RedirectView.as_view(
            pattern_name="abyssal_modules:type_module_list", permanent=True
        ),
    ),
    path(
        "type/<int:type_id>/contracts/",
        abyssal_modules.views.TypedModuleList.as_view(),
        name="type_module_list",
    ),
    path(
        "type/<int:type_id>/hof/",
        abyssal_modules.views.HallOfFameView.as_view(),
        name="type_hall_of_fame",
    ),
    path(
        "type/<int:type_id>/assets/",
        abyssal_modules.views.TypeAssetModuleList.as_view(),
        name="type_asset_module_list",
    ),
    path(
        "type/<int:type_id>/roll/",
        abyssal_modules.views.RollCalculatorView.as_view(),
        name="roll_calculator",
    ),
    path(
        "module/<int:pk>/",
        abyssal_modules.views.ModuleView.as_view(),
        name="module_view",
    ),
    path(
        "module/<int:pk>/image/",
        abyssal_modules.views.ModuleImageView.as_view(),
        name="module_image_view",
    ),
    path(
        "creator/<int:pk>/",
        abyssal_modules.views.CreatorView.as_view(),
        name="creator_view",
    ),
    path(
        "view_contract/",
        abyssal_modules.views.OpenContractView.as_view(),
        name="open_contract",
    ),
    path("appraisal/", abyssal_modules.views.AppraisalView.as_view(), name="appraisal"),
    path(
        "statistics/", abyssal_modules.views.StatisticsList.as_view(), name="statistics"
    ),
    path("", abyssal_modules.views.ModuleList.as_view()),
]

backend/eve_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

import eve_auth.views


app_name = "eve_auth"


urlpatterns = [
    path("login/", eve_auth.views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("callback/", eve_auth.views.CallbackView.as_view(), name="callback"),
    path("profile/", eve_auth.views.ProfileView.as_view(), name="profile"),
]

backend/templates/base.html
{% spaceless %}
{% load static %}
{% load abyssal_types %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
{% endspaceless %}
<html lang="en">
  <head>
    {% if GA_TRACKING_ID %}
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ GA_TRACKING_ID }}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '{{ GA_TRACKING_ID }}');
    </script>
    {% endif %}

    {% if ADSENSE_PUBLISHER_ID %}
    <meta name="google-adsense-account" content="{{ ADSENSE_PUBLISHER_ID }}">
    {% endif %}


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Find and buy abyssal modules all over New Eden with the premier abyssal module market of EVE Online.">

    <meta name="theme-color" content="#862020">
    
    <title>{% block title %}{% endblock %} - Abyssal Market</title>

    {% block metadata %}
    <meta content="Abyssal Market" property="og:title">
    <meta content="Find and buy abyssal modules all over New Eden with the premier abyssal module market of EVE Online." property="og:description">
    <meta content="{% static 'img/mutaplasmid.png' %}" property='og:image'>
    {% endblock %}

    {% block extra_styling %}{% endblock %}

    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}" />

    {% bootstrap_css %}

    <link rel="stylesheet" href="{% static 'css/abyssal.css' %}" />

    <style>
      @import url('https://fonts.googleapis.com/css2?family=Work+Sans&display=swap');
    </style>
  </head>

  <body>
    <script>
      if ((localStorage.getItem('lighting_display_mode') || 'light') == "dark") {
        document.querySelector('body').classList.add('dark-mode');
      }
    </script>

    <input type='hidden' name='csrfmiddlewaretoken' value='{{ csrf_token }}' />

    <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
      <a class="navbar-brand" href="/">Abyssal Market</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-toggled">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar-toggled">
        <ul class="navbar-nav navbar-fill">
          <li class="nav-item dropdown dropdown-accordion" data-accordion="#module-accordion">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside">
              Modules
            </a>
            <div class="dropdown-menu module-dropdown">
              <div class="row mx-2 my-2">
                {% get_abyssal_type_list as type_list %}
                {% for r, l in type_list %}
                  <span class="col-md-3 col-12 align-middle">
                      <img height="21px" src="https://image.eveonline.com/Type/{{ l.0.1 }}_32.png" style="padding-right: 7px;">{{ r }}
                  </span>
                  <div class="col-md-9 col-12 row m-0 p-0">
                      {% for n, i in l %}
                      <span class="col p-1"><a class="btn btn-sm btn-primary btn-block py-0" style="font-size: small;" href="{% url 'abyssal_modules:type_module_list' i %}">{{ n }}</a></span>
                      {% endfor %}
                  </div>
                  <div class="w-100"></div>
                {% endfor %}
              </div>

<!-- 
              <div class="accordion" id="accordionExample">
                {% get_abyssal_type_list as type_list %}
                {% for r, l in type_list %}
                <div class="accordion-item border-0">
                  <h2 class="accordion-header module-accordion-header" id="module-group-heading-{{ l.0.1 }}">
                    <a class="accordion-button btn-sm rounded-0 module-type-header" type="button" data-bs-toggle="collapse" data-bs-target="#module-group-collapse-{{ l.0.1 }}" aria-expanded="false" aria-controls="module-group-collapse-{{ l.0.1 }}">
                      <img height="21px" src="https://image.eveonline.com/Type/{{ l.0.1 }}_32.png" class="pr-2"> {{ r }}
                    </a>
                  </h2>

                  <div id="module-group-collapse-{{ l.0.1 }}" class="accordion-collapse collapse module-type-body" aria-labelledby="module-group-heading-{{ l.0.1 }}" data-parent="#accordionExample">
                    <div class="list-group px-0 py-0">
                      {% for n, i in l %}
                        <a href="{% url 'abyssal_modules:type_module_list' i %}" class="list-group-item list-group-item-action border-0">{{ n }}</a>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div> -->
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'abyssal_modules:appraisal' %}">Appraisal</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'support' %}">Support Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://discord.gg/sFrvsGg">Discord</a>
          </li>
        </ul>
        <ul class="navbar-nav navbar-right">
            <li class="nav-item mr-3">
              <a class="nav-link" href="javascript:toggle_mode()">
                <i class="fa fa-moon-o" aria-hidden="true" id="mode-toggle"></i>
                <span class="d-md-none">Dark/light mode</span>
              </a>
            </li>
          {% if user.is_authenticated %}
            <li class="nav-item dropdown my-auto mr-3">
              <a class="nav-link dropdown-toggle py-0 mr-2" href="#" id="navbar_character_dropdown" role="button" data-toggle="dropdown">
                <img src="https://image.eveonline.com/Character/1_32.jpg" height="32px" class="avatar mr-0" id="current_character_avatar"/>
                <span class="align-middle" id="current_character_name"></span>
              </a>
              <div class="dropdown-menu" id="character_select_list">
              </div>
            </li>
            <li class="nav-item my-auto mr-3">
              <a class="nav-link p-0" href="{% url 'eve_auth:profile' %}">
                <i class="fas fa-user mr-1"></i> Account
              </a>
            </li>
            <li class="nav-item my-auto mr-3">
              <a class="nav-link" href="{% url 'eve_auth:logout' %}">
                <i class="fas fa-sign-out-alt mr-1"></i> Log out
              </a>
            </li>
          {% else %}
            <li class="nav-item my-auto mr-3">
              <a class="nav-link" href="{% url 'eve_auth:login' %}">
                <i class="fas fa-sign-in-alt mr-1"></i> Log in
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container" style="min-height: 56px;"></div>

    {% block content_container %}{% endblock %}

    <div class="container" style="min-height: 56px;"></div>

    <footer class="footer mt-auto py-3 text-light">
      <div class="container">

        Made with &#x1F914;&#x1F52A; by <a href="https://evewho.com/pilot/Sharad+Heft">Sharad Heft</a> &bull; Sharad#4720 &bull; 
        <a href="{% url 'faq' %}">FAQ</a> &bull; 
        <a href="{% url 'legal' %}">Legal</a> &bull; 
        <a href="{% url 'abyssal_modules:statistics' %}">Statistics</a> &bull; 
        <a href="https://github.com/StephenSwat/eve-abyssal-market">GitHub</a>

      </div>
    </footer>

    {{ eve_characters|json_script:'eve_characters' }}

    <script>
      var user_logged_in = {{ user.is_authenticated|yesno:"true,false" }};
    </script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/responsive.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js"></script>
    {% bootstrap_javascript %}
    <script src="{% static 'js/mutaplasmid.js' %}"></script>
    <script src="{% static 'js/dark_mode.js' %}"></script>
    <script src="{% static 'js/character_switch.js' %}"></script>

    <script>
      $('.dropdown-accordion').on('show.bs.dropdown', function (event) {
        console.log("Yyoyoy")
        var accordion = $(this).find($(this).data('accordion'));
        accordion.find('.collapse').collapse('hide');
      });

      $('.dropdown-accordion').on('click', 'a[data-toggle="collapse"]', function (event) {
        console.log("1")
        event.preventDefault();
        event.stopPropagation();
        console.log("2")
        $($(this).data('parent')).find('.panel-collapse.in').collapse('hide');
        $($(this).attr('href')).collapse('show');
      })

    </script>

    {% block trailing_js %} {% endblock %}
  </body>
</html>

backend/templates/content_page.html
{% extends 'base.html' %}

{% block content_container %}
{% block header %}{% endblock header %}

{% block content_tabs %}{% endblock content_tabs %}

{% if ADSENSE_PUBLISHER_ID and ADSENSE_SLOTS.ALL_PAGES_ABOVE_CONTENT %}
<div class="container mb-2">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={{ ADSENSE_PUBLISHER_ID }}"
    crossorigin="anonymous"></script>
<ins class="adsbygoogle"
    style="display:block;width:100%;height:90px"
    data-ad-client="{{ ADSENSE_PUBLISHER_ID }}"
    data-ad-slot="{{ ADSENSE_SLOTS.ALL_PAGES_ABOVE_CONTENT }}"
    data-full-width-responsive="true"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
{% endif %}

<div class="container">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
</div>

{% block content %}{% endblock content %}
{% endblock content_container %}

backend/templates/help.html
{% extends 'content_page.html' %}

{% block title %}Frequently Asked Questions{% endblock %}

{% block header %}
<div class="container-fluid d-flex flex-column ng-scope">
    <div class="row align-items-center bg-primary check-contrast py-5">
        <div class="col-xl-9 container-alt text-light toggles-ignore mx-auto">
            <h1 class="display-3 mb-0">
                <span data-ng-bind="selected.palette.name" class="ng-binding">Frequently Asked Questions</span>
            </h1>
            <p class="lead mb-3"><span data-ng-bind="selected.palette.desc" class="ng-binding">
            Please note that not all questions on this page are actually
            <em>frequently asked</em>. Many of these questions may have been asked only
            once. Others have never been asked at all and are just predictions, made by
            me, of what people could ask me in the future.</p>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container container-narrow my-5">

    <h5>What does this website do?</h5>

    <p>This website scans available public contracts in EVE Online in search of
    abyssal modules. Any abyssal modules found are presented in a (hopefully)
    easily filterable way to make it easy for you to get the modules you
    want.</p>

    <h5>How do I get contracts to show up?</h5>

    <p>The website scans all regions in the game for any public item exchange
    or auction contract with abyssal modules in them.</p>

    <h5>What do the 'M' and 'A' mean next to a module's price?</h5>

    <p>An <strong>M</strong> means the abyssal module is not the only item in
    the contract (there are <em>m</em>ultiple items) and an <strong>A</strong>
    means the contract is an <em>a</em>uction.</p>

    <h5>What do the coloured numbers after a module's stats mean?</h5>

    <p>This is a rating for that stat based on the distribution of that stat
    in the same module group. There is no set minimum or maximum rating for
    a stat, but higher is better. The value shown is the number of quarter
    standard deviations that the value lies from the mean for that module.</p>

    <h5>How do price predictions work?</h5>

    <p>On the module pages for some module types the website will try to give
    you a price estimate for the module you're looking at based on its stats.
    These estimates are calculated by training a support vector regressor every
    day on all past contract data. Estimates are definitely not always
    accurate so you should use your own judgement.</p>

    <h5>How do I view contracts in game?</h5>

    <p>Once you've find a module you like there are two ways to open the
    contract in the EVE client. Firstly, you can click the "log in" button in
    the top right and then the "ESI" button on any abyssal module to
    immediately open it in-game. If you don't want to sign in via EVE SSO you
    can click the "Link" button which will copy some data to your clipboard.
    You can paste this data into your in-game notepad and then click the newly
    created link to view the contract.</p>

    <h5>How can I get in contact with you?</h5>

    <p>Send me an EVE mail. My main character is <a
    href="https://evewho.com/pilot/Sharad+Heft">Sharad Heft</a>. You can also
    send me money if you want, but please don't feel forced.</p>

    <h5>What technologies did you use to build this?</h5>

    <p>The website runs on Django, a popular web development framework for
    Python. In addition, PostgreSQL is used as the database and Huey is a task
    queue that performs all kinds of different tasks. The server used is some
    €10 per month VPS that I rent in the hope that it has enough horsepower to
    run all the terrible code I put on it.</p>

    <h5>Can I see the source code for this website?</h5>

    <p>Of course! It's available <a
    href="https://github.com/StephenSwat/eve-abyssal-market">on GitHub</a>. You
    are also invited to create feature requests and bug reports there.</p>

    <h5>What can you do to me if I log in?</h5>

    <p>I can open contract windows and I can open the information window for
    Exotic Dancers (Male) in your client at random times. The former is
    hopefully helpful and I promise not to do the latter. </p>

    <h5>I have a different question and it isn't listed here and I'm angry!</h5>

    <p>Contact me and I might respond to you and/or add your question to this
    page!</p>

</div>

{% endblock %}

backend/templates/legal.html
{% extends 'content_page.html' %}

{% block title %}Legal Information{% endblock %}

{% block header %}
<div class="container-fluid d-flex flex-column ng-scope">
    <div class="row align-items-center bg-primary check-contrast py-5">
        <div class="col-xl-9 container-alt text-light toggles-ignore mx-auto">
            <h1 class="display-3 mb-0">
                <span data-ng-bind="selected.palette.name" class="ng-binding">Legal</span>
            </h1>
            <p class="lead mb-3"><span data-ng-bind="selected.palette.desc" class="ng-binding">
            I would prefer not to get sued.</p>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container container-narrow my-5">
    <p>mutaplasmid.space uses Google Analytics for site maintenance and
    tracking, which uses cookies. The website administrator has configured
    Google Analytics in accordance with the manual for GDPR compliance
    published by the Dutch Data Protection Authority (DDPA or Autoriteit
    Persoonsgegevens) as published on 2018/08/15 with the exception of the
    recommendation of providing an opt-out. This means that the website
    administrator has: signed a data processing agreement with Google; has
    enabled IP address anonymisation; has disabled data sharing with Google;
    does not use other Google services in conjunction with Google Analytics
    cookies. The service stores potentially identifying data about users who
    have opted to log in, including EVE Online character names, identification
    numbers and OAuth2 access and refresh tokens. As mutaplasmid.space is
    open-source software, it is impossible for the website administrator to
    ensure that the aforementioned information is valid for all other running
    instances of this software. The webserver software used stores access logs
    containing IP addresses and page visits which are stored on a server
    located in the European Union.</p>

    <p>EVE Online and the EVE logo are the registered trademarks of CCP hf. All
    rights are reserved worldwide. All other trademarks are the property of
    their respective owners. EVE Online, the EVE logo, EVE and all associated
    logos and designs are the intellectual property of CCP hf. All artwork,
    screenshots, characters, vehicles, storylines, world facts or other
    recognizable features of the intellectual property relating to these
    trademarks are likewise the intellectual property of CCP hf. CCP hf. has
    granted permission to mutaplasmid.space to use EVE Online and all
    associated logos and designs for promotional and information purposes on
    its website but does not endorse, and is not in any way affiliated with,
    mutaplasmid.space. CCP is in no way responsible for the content on
    or functioning of this website, nor can it be liable for any damage arising
    from the use of this website.</p>

    <p>The source code for mutaplasmid.space is available under the MIT
    license. The full text for this license is included with the source code in
    the file <code>LICENSE</code>.</p>

</div>

{% endblock %}

backend/templates/support.html
{% extends 'content_page.html' %}

{% block title %}Support Us{% endblock %}

{% block header %}
<div class="container-fluid d-flex flex-column ng-scope">
    <div class="row align-items-center bg-primary check-contrast py-5">
        <div class="col-xl-9 container-alt text-light toggles-ignore mx-auto">
            <h1 class="display-3 mb-0">
                <span data-ng-bind="selected.palette.name" class="ng-binding">Support mutaplasmid.space</span>
            </h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container container-narrow my-5">
    <p>mutaplasmid.space has always been and always will be a free website.
    This website exists not as a way for me to make money but rather as a
    service to the community of a game that will forever hold a dear place in
    my heart. That being said, hosting the website takes a considerable amount
    of computing resources which cost money. As the site has grown and has
    gained more users, the costs of running the website have also increased. In
    addition, recent economic developents have driven up the price of
    hosting.</p>

    <p>If you would like to support the development and hosting of the website,
    I am taking donations through a service called Ko-fi. This allows you to
    make one-time donations or recurring payments. Supporting me through Ko-fi
    will allow me to spend more time maintaining and developing new features
    for the website, and it will help keep the site in the air. Please note
    that none of the features on mutaplasmid.space will <b>ever</b> be
    available only to paying users.</p>

    <p>If you are interested in donating any amount to the website, please
    click the button below. Thank you so much for your support.</p>

    <a href='https://ko-fi.com/J3J0HVJ88' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi2.png?v=3' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>
</div>

{% endblock %}